import "./globals.css";
import Header from "@/components/ui/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JustBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen p-0 m-0 box-border flex flex-col`}
      >
        <Header />
        <main className="bg-[#F2F4F7] flex-1">{children}</main>
      </body>
    </html>
  );
}
